-- ============================================================
-- AI Study Planner & Exam Predictor - Oracle Database Setup
-- Run this script in Oracle SQL*Plus or SQL Developer
-- ============================================================

 Drop tables if they exist (run only if resetting)
 DROP TABLE Predictions CASCADE CONSTRAINTS;
 DROP TABLE Progress CASCADE CONSTRAINTS;
 DROP TABLE StudyPlan CASCADE CONSTRAINTS;
 DROP TABLE Syllabus CASCADE CONSTRAINTS;
 DROP TABLE Subjects CASCADE CONSTRAINTS;
 DROP TABLE Users4 CASCADE CONSTRAINTS;
 DROP TABLE Admin1 CASCADE CONSTRAINTS;

-- ─── TABLE: Admin ─────────────────────────────────────────────
CREATE TABLE admin1 (
    admin_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    VARCHAR2(50)  NOT NULL UNIQUE,
    password    VARCHAR2(100) NOT NULL,
    email       VARCHAR2(150),
    created_at  DATE DEFAULT SYSDATE
);

-- ─── TABLE: Users ─────────────────────────────────────────────
CREATE TABLE Users4 (
    user_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name      VARCHAR2(100) NOT NULL,
    email          VARCHAR2(150) NOT NULL UNIQUE,
    phone          VARCHAR2(15),
    password       VARCHAR2(100) NOT NULL,
    academic_level VARCHAR2(20) CHECK (academic_level IN ('SSC','HSC','University')),
    institution    VARCHAR2(200),
    created_at     DATE DEFAULT SYSDATE
);

-- ─── TABLE: Subjects ──────────────────────────────────────────
CREATE TABLE Subjects (
    subject_id     NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        NUMBER NOT NULL REFERENCES Users4(user_id) ON DELETE CASCADE,
    subject_name   VARCHAR2(150) NOT NULL,
    exam_date      DATE,
    total_marks    NUMBER DEFAULT 100
);

-- ─── TABLE: Syllabus ──────────────────────────────────────────
CREATE TABLE Syllabus (
    syllabus_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        NUMBER NOT NULL REFERENCES Users4(user_id) ON DELETE CASCADE,
    subject_id     NUMBER REFERENCES Subjects(subject_id) ON DELETE SET NULL,
    subject_name   VARCHAR2(150),
    content        CLOB,
    uploaded_at    DATE DEFAULT SYSDATE
);

-- ─── TABLE: StudyPlan ─────────────────────────────────────────
CREATE TABLE StudyPlan (
    plan_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        NUMBER NOT NULL REFERENCES Users4(user_id) ON DELETE CASCADE,
    subject_name   VARCHAR2(150),
    plan_date      DATE,
    duration_hrs   NUMBER DEFAULT 2,
    task_desc      VARCHAR2(500),
    status         VARCHAR2(20) DEFAULT 'Pending'
);

-- ─── TABLE: Progress ──────────────────────────────────────────
CREATE TABLE Progress (
    progress_id    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        NUMBER NOT NULL REFERENCES Users4(user_id) ON DELETE CASCADE,
    subject_name   VARCHAR2(150),
    score          NUMBER DEFAULT 0,
    max_score      NUMBER DEFAULT 100,
    recorded_at    DATE DEFAULT SYSDATE
);

-- ─── TABLE: Predictions ───────────────────────────────────────
CREATE TABLE Predictions (
    pred_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_name   VARCHAR2(150),
    chapter        VARCHAR2(200),
    question_text  CLOB,
    question_type  VARCHAR2(20) DEFAULT 'Short',
    difficulty     VARCHAR2(10) DEFAULT 'Medium',
    created_at     DATE DEFAULT SYSDATE
);

-- ─── SEED: Admin ──────────────────────────────────────────────
INSERT INTO admin1(username, password, email)
VALUES ('admin', 'admin123', 'admin@studyplanner.bd');

-- ─── SEED: Sample Predictions ─────────────────────────────────
INSERT INTO Predictions (subject_name, chapter, question_text, question_type, difficulty)
VALUES ('Physics', 'Chapter 1 - Motion', 'Define velocity and acceleration with examples.', 'Short', 'Easy');

INSERT INTO Predictions (subject_name, chapter, question_text, question_type, difficulty)
VALUES ('Physics', 'Chapter 2 - Force', 'State Newton''s three laws of motion and explain each with a real-life example.', 'Creative', 'Medium');

INSERT INTO Predictions (subject_name, chapter, question_text, question_type, difficulty)
VALUES ('Mathematics', 'Chapter 3 - Algebra', 'Solve the quadratic equation: 2x² + 5x - 3 = 0 using the formula method.', 'Problem', 'Medium');

INSERT INTO Predictions (subject_name, chapter, question_text, question_type, difficulty)
VALUES ('Chemistry', 'Chapter 4 - Periodic Table', 'Explain the periodic law and describe the periodic trends of atomic radius.', 'Creative', 'Hard');

INSERT INTO Predictions (subject_name, chapter, question_text, question_type, difficulty)
VALUES ('Biology', 'Chapter 2 - Cell', 'Draw a labeled diagram of a plant cell and describe the functions of each organelle.', 'Creative', 'Medium');

INSERT INTO Predictions (subject_name, chapter, question_text, question_type, difficulty)
VALUES ('English', 'Chapter 1 - Grammar', 'Write a paragraph about the importance of education in Bangladesh (150 words).', 'Short', 'Easy');

COMMIT;

-- ─── VERIFY ───────────────────────────────────────────────────
SELECT 'Admin1 rows: ' || COUNT(*) FROM Admin1;
SELECT 'Predictions rows: ' || COUNT(*) FROM Predictions;
